# Generated by Django 5.0.6 on 2024-07-06 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(default='account/profile_picture/profile.jpg', upload_to='account/profile_picture')),
                ('phone_number', models.IntegerField(default=None, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=10, null=True)),
                ('district', models.CharField(default='Dhaka', max_length=150)),
                ('user_role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountProfile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
