version: '3.9'

services:
  home_housing:
    build: .
    container_name: home_housing_backend
    command: >
      bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 9000:8000
    volumes:
      - .:/home_housing_backend
    