# Generated by Django 5.0.6 on 2024-07-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='about',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='division',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='summary',
            field=models.TextField(),
        ),
    ]
