# Generated by Django 5.0.6 on 2024-10-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0006_alter_advertisement_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimages',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
