# Generated by Django 5.0.6 on 2024-07-06 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rent', '0005_userfavoriteadvertisement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_on', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_properties', to=settings.AUTH_USER_MODEL)),
                ('property_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement_booking', to='rent.advertisement')),
            ],
        ),
    ]
